### PR TITLE
#172 - add echo short tag support

### PR DESCRIPTION
**Pull request by xandros15**

### CODE REVIEW

**Comment by grappler** [comment]
There is no need to add a constant to enable the echo short tag. You can directly allow it.

**Comment by xandros15** [comment]
I prefer to control some things by constants (or shows that option can be change), but if you insist...

**Comment by Otto42** [comment]
Why would we allow short echo's? Those should not be used. They don't work in PHP < 5.4.

**Comment by pattonwebz** [comment]
Since core php recommendation is now 5.6 and that in 5.4 short echo tags were decoupled from the [short_open_tag](https://www.php.net/manual/en/ini.core.php#ini.short-open-tag) setting the only reason I see that we should continue to disallow these is for sake of consistency - core does not use short echo tags anywhere.

My personal preference would be to continue using the full syntax but there is no longer a technical reason to keep these in the disallow regex.

**Comment by dingo-d** [comment]
The WPCS clearly states not to allow them: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#no-shorthand-php-tags.

While I agree that themes shouldn't follow WPCS, should we try to be as consistent as possible with them?

**Comment by joyously** [comment]
For me, this is one of those things that falls into "we don't have just any theme, we have the best themes" sentiment. Themes should be readable, and short echo tags are not (for the average coder).
I would keep them in the disallow regex for consistency with core and legacy themes.

**Comment by carolinan** [comment]
For consistency, we will not add support for this, so, closing.

**Pull request closed without merging**
