### PR TITLE
Remove block-patterns recommendations

### PR DESCRIPTION
**Pull request by aristath**
Block-patterns are not a requirement. It may be desirable for a theme to have block-patterns, but that is rather opinionated and not all themes should have patterns. A pattern is basically just reusable content and has absolutely nothing to do with a theme. This should not exist in the theme-check plugin.

### CODE REVIEW

**Comment by carolinan** [comment]
I would prefer to have it changed to info in that case because many authors don't know that these are allowed.

**Comment by aristath** [comment]
Is the role of theme-check to inform theme-authors that they can do something? :thinking:

**Comment by carolinan** [comment]
The plugin reaches more theme authors than themes team can alone. So yes, when there are new features that we want to establish.

**Comment by aristath** [comment]
Closing this one after discussing further.

**Pull request closed without merging**
