### PR TITLE
Add Check for Affiliate Links

### PR DESCRIPTION
**Pull request by aaronjorbin**
Some basic checks for known affiliate link code. Inspired by some of the code in https://github.com/brainstormforce/astra/commit/b3f7369eaaae128b451c2021bfcd8b8c3aaec45d

### CODE REVIEW

**Comment by pattonwebz** [comment]
I have done some very basic initial tests on this PR and it seems to function as expected.

**Comment by acosmin** [comment]
@aaronjorbin If you could also add these ones :) It would be great:
https://wpdirectory.net/search/01EF4V4ATY7GV50PP5S712N7J2
https://wpdirectory.net/search/01EF4V5TAQFS4RDXTJ8XAAA64C

Thanks!

**Comment by pattonwebz** [comment]
@acosmin I can't see a good way to match the 2nd search there as it seems like it can be used in help articles as well but the first one can be just an exact match. Will see about adding that and do a little more testing on this :)

**Comment by pattonwebz** [comment]
@acosmin I managed to add a check that caught both. Can you test this to verify it works as expected?

**Comment by acosmin** [comment]
@pattonwebz looks ok to me 👍

**Comment by aaronjorbin** [comment]
That change looks good to me to

**Pull request merged**
