### PR TITLE
Check if style.css is using on tag twice

### LINKED ISSUE #178: Check for duplicate theme tags in style.css
I've often seen themes using one theme tag twice in the style.css, so this will prevent that. Just to not cause confusion, I'm talking about Theme Tags (featured-image, translation-ready, post-formats...) not CSS tags.

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Checks if the theme's style.css file is using one theme tag more than once. Close #178

### CODE REVIEW

**Comment by grappler** [comment]
If it is going to fail the theme check then it should be a Required notice and not a Warning.

**Comment by HardeepAsrani** [comment]
Yup, I agree. I used warning my mistake. Will send an update. :)

**Comment by HardeepAsrani** [comment]
@grappler There you go. :)

**Comment by grappler** [comment]
You need to update the class too but wait for me to test the code first.

**Comment by HardeepAsrani** [comment]
@grappler I actually didn't notice that. 😞

Let me know when you test and I'll update the code. :)

**Comment by grappler** [comment]
Ok, it works as expected.

**Comment by HardeepAsrani** [comment]
@grappler And I've updated the pull. Let me know if there's anything else. :)

**Comment by grappler** [comment]
As I merged another PR this is now failing.

- Please update your master branch from this master branch. Doc: https://help.github.com/articles/syncing-a-fork
- Run `git checkout issue-178` then `git reset --hard master`  to delete your changes and update your branch with the latest changes.
- Reapply your changes and commit them
- Then run `git push --force` to override the commits on GitHub.

**Pull request closed without merging**
